### ISSUE TITLE
after update of Wlinux to version 1.1.26.0 expolrer integration does not work at all 

### ISSUE THREAD

**Issue by michalkvasnicka** [WhitewaterFoundry/WLinux#246] opened 2018-12-03 18:34 UTC
Hi guys,
WLinux is probably still in development phase, because there are still terrible problems with windows explorer integration. I do not believe that you are selling this completely unreliable application on Microsoft Store.

After update  to version 1.1.26.0 is completely not possible to open Wlinux by right click menu:

error message: Application not found

**### Do something ASAP!!! But especially, do not want the money for this fatal application !!!**

**Comment by sirredbeard** [comment] 2018-12-03 18:53
Closed as a dupe of #195.

**Closed by sirredbeard** 2018-12-03 18:53 UTC
