### ISSUE TITLE
Use windows remote desktop connection

### ISSUE THREAD

**Issue by mayankmetha** [WhitewaterFoundry/WLinux#33] opened 2018-09-24 15:26 UTC
Make use of windows remote desktop connection to run gui based linux apps on windows

**Comment by sirredbeard** [comment] 2018-09-24 16:10
Could you elaborate a bit more on what you had in mind?

People are already doing things with xrdp and WSL: https://www.youtube.com/watch?v=JcmGaGS2Gpc

**Comment by sirredbeard** [comment] 2018-09-24 16:14
Closing as a duplicate of #19.

**Closed by sirredbeard** 2018-09-24 16:14 UTC
Labels: Triage
