### ISSUE TITLE
Black lines on run  wlinux-setup

### ISSUE THREAD

**Issue by elswerky** [WhitewaterFoundry/WLinux#266] opened 2018-12-19 02:29 UTC
i bought wlinux today in hope that i will find it better than other availabe linux terminals in microsoft store to be surprised that no apparent advantage of wlinux over other free linux terminals on store 

- even you don't provide any tutorials on how to install environmental desktops or anything 

you just typed some advantages without any tutorial on how to run them 

i wanted to install deepin desktop or gnome but didn''t find any tutorial provided by you 
even you didn't provide a tutorial on  how to install xfce4 !

and now when i run **$  wlinux-setup **  i get this black lines on terminal 

really i was shocked by it and don't see advanced features that make one pay for it .

![wlinux bug](https://user-images.githubusercontent.com/26687459/50195152-95f58380-0346-11e9-91e9-0b50fc32aafb.PNG)

**Comment by patrick330602** [comment] 2018-12-19 03:46
are you using the build 18298? This is a known bug in Insider version caused by the new rendering system in conhost.exe, it happens to WSL git too, and a lot of other apps involving `curses`. it supposed to be fixed in [next build](https://github.com/Microsoft/console/issues/325).

**Comment by elswerky** [comment] 2018-12-19 03:48
> are you using the build 18298? This is a known bug in Insider version caused by the new rendering system in conhost.exe, it happens to WSL git too, and a lot of other apps involving `curses`. it supposed to be fixed in [next build](https://github.com/Microsoft/console/issues/325).

yes i am using this build 

pls can you provide tutorial on how to installl diffrent desktop environments on wlinux ??

**Comment by patrick330602** [comment] 2018-12-19 04:00
> pls can you provide tutorial on how to installl diffrent desktop environments on wlinux ??

We currently do not have any tutorial on that, but as you suggest, we can help implement installing DE from `wlinux-setup`, thanks for the suggestion.

Here is some of them written by myself before which could apply to WLinux:
OpenBox: http://patrickwu.space/2017/03/02/openbox-tint2-windows10/
Unity & Xfce(Really Old): http://patrickwu.space/2016/08/23/LDE-On-Windows-With-Chinese/

Also there is some tutorial provided by X410, which also can be applied to WLinux:
Xfce: https://token2shell.com/howto/x410/customizing-xfce-desktop-for-ubuntu-wsl/
Pantheon Desktop: https://token2shell.com/howto/x410/installing-pantheon-desktop-on-ubuntu-wsl/

**Comment by elswerky** [comment] 2018-12-19 04:02
@patrick330602 
Thank you very much 
hope you integrate it to wlinux setup soon to be easy to install and run full desktop environment 


also i hope you apply soon a new terminal based on arch

**Closed** 2019-03-09 17:17 UTC
Labels: Feature Enhancement, Upstream Issue, User Support
