### ISSUE TITLE
Scrolling issue when using Clear

### ISSUE THREAD

**Issue by kurtbitner** [WhitewaterFoundry/WLinux#199] opened 2018-11-19 21:07 UTC
Whenever I run wlinux-setup, I can choose the options, but then after I select them I just get a black screen and nothing happens.

I open up resmon and I don't see any apt processes running.

**Comment by kurtbitner** [comment] 2018-11-19 21:18
I found the glitch - when it prompts you for the shell change, you have to scroll up a few lines to see the prompt. Can you add this to a later fix? Thanks.

**Comment by sirredbeard** [comment] 2018-11-19 21:41
I noticed this behavior too and will take a look into it. I think it happens after '$ clear' is issued.

**Comment by sirredbeard** [comment] 2018-11-19 21:41
What build of Windows 10 are you on?

**Comment by sirredbeard** [comment] 2018-11-19 22:03
I believe the issue is the use of the clear command [here](https://github.com/WhitewaterFoundry/WLinux/blob/61beea370383d0291064332950b421cd0c934c67/linux_files/setup#L227).

I can reproduce it elsewhere using clear, but not clear -x.

The temporary workaround is to alias clear="clear -x"

I am unable to reproduce this on Debian. clear is provided by ncurses and they are running the same version.

I cannot think of any changes we made that would affecting scrolling behavior.

**Comment by grufwub** [comment] 2018-11-22 13:12
There do seem to be some inconsistencies with the way that the default WSL console window reacts when the 'clear' command is issued. 

'clear' is meant to clear (including scroll-buffer) while 'clear -x' only clears what is currently on screen pushing it back in the scroll-buffer. But under the default WSL console window both perform what would usually happen with a regularly issued 'clear -x'. Yet if I run xfce4-terminal (in my case, under X410) 'clear' and 'clear -x' both perform as intended.

So this might not be an issue at our end?

**Comment by sirredbeard** [comment] 2018-11-22 13:57
I wonder if this is an issue that was introduced in the console updates in RS5. 

The trouble is I can’t reproduce on Debian WSL distro.

**Comment by patrick330602** [comment] 2018-11-29 07:38
Just noticed this bug from a friend, and more specifically, this bug seems to related to console that set their code page as 65001 UTF-8 in Windows 10 1809(but the bug seems fixed in Insider build)

**Comment by grufwub** [comment] 2018-11-29 13:35
Ah that does make sense, I ran into issues previously with the windows console code page with a Python script I wrote, but never had the issue on Linux.

**Closed** 2018-12-03 14:18 UTC
Labels: Bug, Triage, Upstream Issue
