### ISSUE TITLE
Allow Windows to access WSL files via webdav (or something else)

### ISSUE THREAD

**Issue by cspotcode** [WhitewaterFoundry/WLinux#250] opened 2018-12-05 23:06 UTC
**Is your feature request related to a problem? Please describe.**

I can't manipulate WSL files (for example `~/.bashrc`) in Windows programs. (for example notepad or my Windows copy of VSCode)

**Describe the solution you'd like**

A pre-configured solution for mounting my WSL home directory as a drive in Windows Explorer.  So if I want to open a Linux config file in Notepad, I can find it in Windows Explorer.

**Describe alternatives you've considered**

I wrote a script to launch a WebDav server that hosts my WSL home directory.  Then I mount that webdav server (http://localhost:2387/) as W:\ in Windows Explorer.  It's slow but it does the trick.  I can open `W:\` in Windows Explorer and see my WSL home directory.

WebDav is the only solution that worked for me.  I've heard about people setting up Samba or NFS servers or using SFTP.  As far as I know, the only filesystems that Windows can mount as drives are Sambda, WebDav, or NFS.  But NFS has to be enabled via "Turn Windows Features On or Off" and there aren't any good user-mode NFS servers on Linux.  I couldn't make Samba work; perhaps because it uses multiple ports that conflict with Windows' Samba server.  Mounting SFTP requires [Dokany](https://github.com/dokan-dev/dokany).

**Comment by DarthSpock** [comment] 2019-01-07 14:06
> I can't manipulate WSL files (for example ~/.bashrc) in Windows programs. (for example notepad or my Windows copy of VSCode)

So you actually can safely modify Linux files using VS Code if you have the metadata feature enabled (which Wlinux does by default) via `wsl.conf` (so it persists across sessions). The problem is when you attempt to save your file the metadata gets overwritten. This is why most editors can't be used (including notepad). They need to update to account for the feature in WSL (which stems from how much user demand there is for such support). Automatically creating a samba share on Wlinux wouldn't be unreasonable though if VS Code isn't your IDE of choice. But I wonder if Samba would recognize the metadata presented by WSL (it's not the same as pure Linux). I'm sure they could take a PR, just like NTFS-3G could also take a PR to account for it for example.

**Comment by DarthSpock** [comment] 2019-01-07 14:13
>A pre-configured solution for mounting my WSL home directory as a drive in Windows Explorer. So if I want to open a Linux config file in Notepad, I can find it in Windows Explorer.

Well if you know where your root file system lives in AppData, you could create a local share. Never done it via CLI but the PS commands ought to be simple and easy enough to do it in an automated fashion when installing Wlinux.

**Comment by mikart143** [comment] 2019-02-21 09:59
There is going to be a feature for exploring wsl files from windows file explorer in april update.
[https://meterpreter.org/access-wsl-filesystem-windows-explorer/?cn-reloaded=1](url)
In my opinion this will resolve this issue.
I know this is not the best website with news.

**Comment by DarthSpock** [comment] 2019-02-21 13:36
The official source which took less than 2 seconds to search on google. https://blogs.msdn.microsoft.com/commandline/2019/02/15/whats-new-for-wsl-in-windows-10-version-1903/

**Comment by sirredbeard** [comment] 2019-03-09 17:16
Closing this in light of the new feature coming to Windows 10.

**Closed by sirredbeard** 2019-03-09 17:16 UTC
Labels: Feature Enhancement, For Discussion
