### ISSUE TITLE
apt install build-essentials is broken in 1.1.16

### ISSUE THREAD

**Issue by Ozzy878** [WhitewaterFoundry/WLinux#48] opened 2018-09-26 18:12 UTC
Trouble running gcc programs with the common C libraries, and build-essential apt is not installing properly.

**Comment by sirredbeard** [comment] 2018-09-26 18:30
The cause is that the default install in 1.1.16 ships with python 3.7 from testing branch which brings in build-essential from testing branch and this has caused unforeseen problems.

You can fix this for now with:

`$ sudo apt-get -t testing install build-essential`

We are not going to be mixing stretch and testing in the default install after the new setup script is released, users will be able to pick if they want python or other packages installed or not.

Sorry this has caused you a problem.

We shouldn't have crossed the streams.

**Comment by sirredbeard** [comment] 2018-09-26 18:52
I was able to duplicate your issue from a clean install and tested the workaround.

We have committed a PR for the next maintenance release to address this.

Let me know if you run into any more problems. 

Thank you for supporting WLinux. Stay tuned for the new setup process.

**Closed by sirredbeard** 2018-09-26 18:52 UTC
Labels: Bug, Patched, Workaround

**Comment by Ozzy878** [comment] 2018-09-26 19:04
Perfect, thank you for the update.. "$ sudo apt-get -t testing install build-essential" seemed to do do the trick.
